/*
  This module accepts the parse tree generated by the parser,
  evaluates each item, and produces the output code to run in js with evaluator.
*/

var _ = require('../bower_components/lodash/dist/lodash');
var l = function(c) {
    console.log(c)
}

exports.run = function(string) {
    try {
        return eval(string)
    } catch (exception) {
        return exception.message// + "\n" + exception.stack;
    }
}
